# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitls < Formula
  desc "Listing git repository from URL/User/Org"
  homepage "https://github.com/hahwul/gitls"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/gitls/releases/download/v1.0.3/gitls_1.0.3_darwin_amd64.tar.gz"
      sha256 "5da8caf312abb22ee606e8cbf617335ab92865bee59463674cca44f2ef6172e7"

      def install
        bin.install "gitls"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hahwul/gitls/releases/download/v1.0.3/gitls_1.0.3_darwin_arm64.tar.gz"
      sha256 "b6a6253f0a5e2c22026a9f25e5561fd714c22b73ecc9f888f3bd471816bd0e32"

      def install
        bin.install "gitls"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/gitls/releases/download/v1.0.3/gitls_1.0.3_linux_armv6.tar.gz"
      sha256 "a32210ceecf65ad85b16902b13f1b78a1fc9e7177bcdfecf963e7740bed665eb"

      def install
        bin.install "gitls"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hahwul/gitls/releases/download/v1.0.3/gitls_1.0.3_linux_arm64.tar.gz"
      sha256 "35165ca26286ee8b0f983b3ad5ccf427bda93ee32615e9953eb4cde4fa617497"

      def install
        bin.install "gitls"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hahwul/gitls/releases/download/v1.0.3/gitls_1.0.3_linux_amd64.tar.gz"
      sha256 "1aaa18be7d8b5db0fb88b00140e11b264cf2f2b4cdcbaf7e1030405092268d48"

      def install
        bin.install "gitls"
      end
    end
  end

  test do
    system "#{bin}/gitls -version"
  end
end
