# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitls < Formula
  desc "Listing git repository from URL/User/Org"
  homepage "https://github.com/hahwul/gitls"
  version "1.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/hahwul/gitls/releases/download/v1.0.2/gitls_1.0.2_darwin_amd64.tar.gz"
    sha256 "a3ecffdf5f449a83787b2e77fd157eabb019e49eb799f7e5711a73ac26fe641f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hahwul/gitls/releases/download/v1.0.2/gitls_1.0.2_linux_amd64.tar.gz"
    sha256 "5f465740550e392f96d7e50e2e30b2838409ddd4f820c1bc2261cb7705eec911"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/hahwul/gitls/releases/download/v1.0.2/gitls_1.0.2_linux_armv6.tar.gz"
    sha256 "8ed8630e1176ec28867f214b589d393e82b84d0ce1b7d7c5270ba6649d5b3863"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hahwul/gitls/releases/download/v1.0.2/gitls_1.0.2_linux_arm64.tar.gz"
    sha256 "fc54351d892e5f53353826ac10ea30d2e51e0f9db7590b8836f64e87a88d4b4d"
  end

  def install
    bin.install "gitls"
  end

  test do
    system "#{bin}/gitls -version"
  end
end
